app/mod_admin/controllers.py
from datetime import date
from threading import Thread
from time import strptime, mktime

import bcrypt
import requests
from app import app, db, mail
from app.mod_site.controllers import is_integer, is_date, is_category, category_map
from app.models import Users, QueuedScores, Scores, NewArchers, Archers, BowTypes, Rounds, Events, WingEntries
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, login_user, current_user, logout_user
from flask_mail import Message

# Use the C ElementTree implementation where possible
try:
    from xml.etree.cElementTree import ElementTree, fromstring
except ImportError:
    from xml.etree.ElementTree import ElementTree, fromstring

mod_admin = Blueprint('admin', __name__, url_prefix='/records/admin')


@mod_admin.route('/', methods=['GET'])
@login_required
def dashboard():
    return render_template('admin/dashboard.html')


@mod_admin.route('/score/<int:score_id>/approve', methods=['GET'])
@login_required
def approve_score(score_id):
    score = QueuedScores.query.get(score_id)

    if score is None:
        flash('Score doesn\'t exist', 'score')
        return redirect(url_for('.dashboard'))
    else:
        approved = Scores(score.archer_id, score.round_id, score.event_id, score.bow_type, score.category, score.score,
                          score.num_hits, score.num_golds, score.num_xs, score.date)

        db.session.add(approved)
        db.session.delete(score)
        db.session.commit()

        flash('Score approved successfully', 'score')
        return redirect(url_for('.dashboard'))


@mod_admin.route('/score/add', methods=['GET'])
@login_required
def add_score():
    return render_template('admin/score-add.html', bow_types=BowTypes.query.order_by(db.desc(BowTypes.id)).all())


@mod_admin.route('/score/<int:score_id>/reject', methods=['GET'])
@login_required
def reject_score(score_id):
    score = QueuedScores.query.get(score_id)

    if score is None:
        flash('Score doesn\'t exist', 'score')
        return redirect(url_for('.dashboard'))
    else:
        db.session.delete(score)
        db.session.commit()

        flash('Score rejected successfully', 'score')
        return redirect(url_for('.dashboard'))


@mod_admin.route('/scores/queued', methods=['GET'])
@login_required
def approve_scores():
    return render_template('admin/scores-approve.html', scores=QueuedScores.query.all())


@mod_admin.route('/scores/queued/update', methods=['POST'])
@login_required
def update_score_status():
    updated_count = 0

    for item in request.form.iteritems():
        score_id, status = item

        if 'csrf_token' in score_id:
            continue

        score = QueuedScores.query.get(score_id)

        if not score:
            continue

        if 'A' in status:
            db.session.add(Scores(score.archer_id, score.round_id, score.event_id, score.bow_type, score.category,
                                  score.score, score.num_hits, score.num_golds, score.num_xs, score.date))
            db.session.delete(score)

            updated_count += 1
        elif 'R' in status:
            db.session.delete(score)

            updated_count += 1
        else:
            continue

    db.session.commit()

    if updated_count > 0:
        flash('{num} scores{s} updated successfully'.format(num=updated_count, s='s' if updated_count > 1 else ''),
              'submission')

    return redirect(url_for('.approve_scores'))


@mod_admin.route('/score/<int:score_id>/edit', methods=['GET'])
@login_required
def edit_score(score_id):
    score = Scores.query.get(score_id)

    if not score:
        return redirect(url_for('.dashboard'))

    try:
        next_url = request.args['next']
    except KeyError:
        next_url = url_for('.dashboard')

    return render_template('admin/score-edit.html', score=score, next=next_url, bow_types=BowTypes.query.all())


@mod_admin.route('/score/update', methods=['POST'])
@login_required
def update_score():
    try:
        if not request.form['bow-select'] or \
                not request.form['archer-select'] or \
                not request.form['round-select'] or \
                not request.form['event-select'] or \
                not request.form['category-select'] or \
                not request.form['date-input'] or \
                not request.form['score-hits'] or \
                not request.form['score-score'] or \
                not request.form['score-golds'] or \
                not request.form['score-id'] or \
                not request.form['origin']:
            flash('Incomplete score', 'submission')
            return redirect(request.form['origin'])
    except KeyError:
        flash('Incomplete score', 'submission')
        return redirect(url_for('.dashboard'))

    if 'score-xs' in request.form:
        if not request.form['score-xs']:
            flash('Incomplete score', 'submission')
            return redirect(request.form['origin'])

    if not is_integer(request.form['bow-select']) or \
            not is_integer(request.form['archer-select']) or \
            not is_integer(request.form['round-select']) or \
            not is_integer(request.form['event-select']) or \
            not is_category(request.form['category-select']) or \
            not is_date(request.form['date-input']) or \
            not is_integer(request.form['score-hits']) or \
            not is_integer(request.form['score-score']) or \
            not is_integer(request.form['score-golds']) or \
            not is_integer(request.form['score-id']):
        flash('Unexpected score information type', 'submission')
        return redirect(request.form['origin'])

    if 'score-xs' in request.form:
        if not is_integer(request.form['score-xs']):
            flash('Unexpected score information type', 'submission')
            return redirect(request.form['origin'])

    if not db.session.query(db.exists().where(Archers.id == request.form['archer-select'])).scalar():
        flash('Archer doesn\'t exist', 'submission')
        return redirect(request.form['origin'])
    archer = Archers.query.get(request.form['archer-select'])

    if not db.session.query(db.exists().where(Rounds.id == request.form['round-select'])).scalar():
        flash('Round doesn\'t exist', 'submission')
        return redirect(request.form['origin'])
    score_round = Rounds.query.get(request.form['round-select'])

    if not db.session.query(db.exists().where(Events.id == request.form['event-select'])).scalar():
        flash('Event doesn\'t exist', 'submission')
        return redirect(request.form['origin'])
    event = Events.query.get(request.form['event-select'])

    if not db.session.query(db.exists().where(BowTypes.id == request.form['bow-select'])).scalar():
        flash('Bow type doesn\'t exist', 'submission')
        return redirect(request.form['origin'])
    bow_type = BowTypes.query.get(request.form['bow-select'])

    if int(request.form['score-hits']) not in range(0, score_round.max_hits + 1):
        flash('Incorrect number of hits', 'submission')
        return redirect(request.form['origin'])
    hits = int(request.form['score-hits'])

    if int(request.form['score-golds']) not in range(0, score_round.max_hits + 1):
        flash('Incorrect number of golds', 'submission')
        return redirect(request.form['origin'])
    golds = int(request.form['score-golds'])

    if 'score-xs' in request.form:
        if int(request.form['score-xs']) not in range(0, golds + 1):
            flash('Incorrect number of Xs', 'submission')
            return redirect(request.form['origin'])
        else:
            if score_round.r_type is 'Clout' or 'Indoors' in score_round.r_type:
                xs = None
            else:
                xs = int(request.form['score-xs'])
    else:
        if score_round.r_type is 'Clout' or 'Indoors' in score_round.r_type:
            xs = None
        else:
            xs = 0

    if int(request.form['score-score']) not in range(0, score_round.max_score + 1):
        flash('Incorrect score', 'submission')
        return redirect(request.form['origin'])
    score = int(request.form['score-score'])

    category = category_map(request.form['category-select'])
    score_date = date.fromtimestamp(mktime(strptime(request.form['date-input'], '%Y-%m-%d')))

    try:
        new_score = 'new' in request.form['score-status']
    except KeyError:
        new_score = False

    if new_score:
        score_obj = Scores(archer.id, score_round.id, event.id, bow_type.id, category, score, hits, golds, xs,
                           score_date)

        db.session.add(score_obj)

        flash('Added new score successfully', 'submission')
    else:
        old_score = Scores.query.get(int(request.form['score-id']))

        if not old_score:
            flash('Original score doesn\'t exist', 'submission')
            return redirect(request.form['origin'])

        old_score.archer_id = archer.id
        old_score.round_id = score_round.id
        old_score.event_id = event.id
        old_score.bow_type = bow_type.id
        old_score.category = category
        old_score.score = score
        old_score.num_hits = hits
        old_score.num_golds = golds
        old_score.num_xs = xs
        old_score.date = score_date

        flash('Updated score successfully', 'submission')

    db.session.commit()

    if new_score:
        return redirect(url_for('admin.add_score'))
    else:
        try:
            return redirect(request.form['origin'])
        except KeyError:
            return redirect(url_for('.dashboard'))


@mod_admin.route('/score/<int:score_id>/delete', methods=['GET'])
@login_required
def delete_score(score_id):
    score = Scores.query.get(score_id)

    if not score:
        try:
            flash('Score doesn\'t exist', 'submission')
            return redirect(request.args['next'])
        except KeyError:

app/templates/site/all-records.html
{% extends 'base.html' %}

{% block title %}All individual club records - University of Warwick Archery Club{% endblock %}

{% block main_content %}
    {% include "site/search-form.html" %}
    <div class="row">
        <div class="small-12 columns">
            <h1>All individual club records</h1>
            <ul class="tabs" data-tab>
                <li class="tab-title active"><a href="#indoors">Indoors</a></li>
                <li class="tab-title"><a href="#outdoors">Outdoors</a></li>
            </ul>
            <div class="tabs-content">
                <div class="content active" id="indoors">
                    {% for category in indoor_categories %}
                        <div class="row">
                            <div class="small-12 columns">
                                <h3 class="bottom-divider">{{ category['name'] }}</h3>
                                <table class="full-width">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Round</th>
                                        <th>Score/Golds</th>
                                        <th>Category</th>
                                        <th>Date</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for score in category['scores'] %}
                                        <tr>
                                        <td>{{ score.archer_name }}</td>
                                        <td>{{ score.round_name }}</td>
                                        <td>{{ "{}/{}".format(score.score, (score.num_golds if score.num_golds else 0)) }}</td>
                                        <td>{{ "{} {}".format(score.category, ("Gents" if score.gender == 'M' else "Ladies")) }}</td>
                                        <td>{{ score.date }}</td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="content" id="outdoors">
                    {% for category in outdoor_categories %}
                        <div class="row">
                            <div class="small-12 columns">
                                <h3 class="bottom-divider">{{ category['name'] }}</h3>
                                <table class="full-width">
                                    <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Round</th>
                                        <th>Score/Golds</th>
                                        <th>Category</th>
                                        <th>Date</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for score in category['scores'] %}
                                        <tr>
                                        <td>{{ score.archer_name }}</td>
                                        <td>{{ score.round_name }}</td>
                                        <td>{{ "{}/{}".format(score.score, (score.num_golds if score.num_golds else 0)) }}</td>
                                        <td>{{ "{} {}".format(score.category, ("Gents" if score.gender == 'M' else "Ladies")) }}</td>
                                        <td>{{ score.date }}</td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var csrftoken = "{{ csrf_token() }}"
    </script>
    <script src="{{ url_for('static', filename='js/jquery.autocomplete.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/select2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/records-search.js') }}"></script>
{% endblock %}

app/templates/site/archer.html
{% extends 'base.html' %}

{% block title %}
    {{ archer.get_name() + ' - University of Warwick Archery Club' }}
{% endblock %}

{% block main_content %}
    {% include "site/search-form.html" %}
    <div class="row">
        <div class="small-12 columns">
            <section>
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('admin.edit_member_id', member_id=archer.id) }}"><i class="fa fa-pencil"></i>
                        Edit member</a>
                {% endif %}
                <h1>
                    Scores for {{ archer.get_name() }}
                </h1>
                <h4>Jump to:</h4>
                <ul>
                    {% for category in categories %}
                        <li>
                            <a class="category-link"
                               href="#{{ category['div_name'] | lower | strip_spaces | e }}">{{ category['div_name'] }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <p class="bottom-divider pad-bottom px-5"><strong>Note:</strong> Any classification with an asterix
                    (<strong>*</strong>) needs to have been shot at a record-status event.</p>
            </section>
            {% for category in categories %}
                <section>
                    <a href="/records/round/{{ category["round_id"] }}">
                        <h3 id="{{ category['div_name'] | lower | strip_spaces | e }}">{{ category['div_name'] }}</h3>
                    </a>
                    <table class="full-width sortable">
                        <thead>
                        <tr>
                            <th class="{sorter: 'scores'} sort-header sort-ascending">Score</th>
                            <th class="sort-header">Hits</th>
                            <th class="sort-header">Golds</th>
                            <th class="sort-header">Xs</th>
                            <th class="sort-header reverse">Experience</th>
                            <th>Classification</th>
                            <th class="sort-header">Date</th>
                            <th class="sort-header">Event</th>
                            {% if current_user.is_authenticated %}
                                <th>Actions</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for score in category['scores'] %}
                            <tr>
                                <td>{{ score['score'] }}<span class="fade">/{{ category['max_score'] }}</span></td>
                                <td>{{ score['num_hits'] }}</td>
                                <td>{{ score['num_golds'] }}</td>
                                <td>{{ score['num_xs'] }}</td>
                                <td>{{ score['category'] }}</td>
                                <td>{{ score['classification'] if score['classification'] else 'None' }}</td>
                                <td>{{ score['date'] }}</td>
                                <td>{{ score['event'].name }}</td>
                                {% if current_user.is_authenticated %}
                                    <td>
                                        <a class="admin-action"
                                           href="{{ url_for('admin.edit_score', score_id=score.id) }}?next={{ request.path | urlencode }}"><i
                                                class="fa fa-pencil"></i> Edit</a>
                                        <a class="admin-action"
                                           href="{{ url_for('admin.delete_score', score_id=score.id) }}?next={{ request.path | urlencode }}"><i
                                                class="fa fa-trash"></i> Delete</a>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="text-right"><a class="category-link" href="#top"><i class="fa fa-chevron-up"></i> Back to
                        the top</a></p>
                </section>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var class_column = 5;
        var csrftoken = "{{ csrf_token() }}"
    </script>
    <script src="{{ url_for('static', filename='js/jquery.autocomplete.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/select2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/records-search.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.tablesorter.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/sort-tables.js') }}"></script>
    <script src="{{ url_for('static', filename='js/chutney.js') }}"></script>
    <script src="https://code.jquery.com/ui/1.11.3/jquery-ui.min.js"></script>
{% endblock %}

app/templates/site/event-detail.html
{% extends 'base.html' %}

{% block title %}
    {{ event.name + ' on ' + date + ' - University of Warwick Archery Club' }}
{% endblock %}

{% block main_content %}
    {% include "site/search-form.html" %}
    <div class="row">
        <div class="small-12 columns">
            <section>
                <h1>{{ event.name }} on {{ date }}</h1>
                <h4>Jump to:</h4>
                <ul>
                    {% for category in categories %}
                        <li>
                            <a class="category-link"
                               href="#{{ category['div_name'] | lower | strip_spaces }}">{{ category['div_name'] }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <p class="bottom-divider pad-bottom px-5"><strong>Note:</strong> Any classification with an asterix (<strong>*</strong>) needs to have been shot at a record-status event.</p>
            </section>
            {% for category in categories %}
                <section>
                    <a href="/records/round/{{ category["round_id"] }}">
                        <h3 id="{{ category['div_name'] | lower | strip_spaces }}">{{ category['div_name'] }}</h3>
                    </a>
                    <table class="full-width sortable">
                        <thead>
                        <tr>
                            <th class="sort-header reverse">Name</th>
                            <th class="{sorter: 'scores'} sort-header sort-ascending">Score</th>
                            <th class="sort-header">Hits</th>
                            <th class="sort-header">Golds</th>
                            <th class="sort-header">Xs</th>
                            <th class="sort-header reverse">Experience</th>
                            <th>Classification</th>
                            <th class="sort-header">Date</th>
                            {% if current_user.is_authenticated %}
                                <th>Actions</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for score in category['scores'] %}
                            <tr>
                                <td><a href="/records/archer/{{ score.archer_id }}">{{ score.archer.get_name() }}</a></td>
                                <td>{{ score['score'] }}<span class="fade">/{{ category['max_score'] }}</span></td>
                                <td>{{ score['num_hits'] }}</td>
                                <td>{{ score['num_golds'] }}</td>
                                <td>{{ score['num_xs'] }}</td>
                                <td>{{ score['category'] }}</td>
                                <td>{{ score['classification'] if score['classification'] else '' }}</td>
                                <td>{{ score['date'] }}</td>
                                {% if current_user.is_authenticated %}
                                    <td>
                                        <a class="admin-action"
                                           href="{{ url_for('admin.edit_score', score_id=score.id) }}?next={{ request.path | urlencode }}"><i
                                                class="fa fa-pencil"></i> Edit</a>
                                        <a class="admin-action"
                                           href="{{ url_for('admin.delete_score', score_id=score.id) }}?next={{ request.path | urlencode }}"><i
                                                class="fa fa-trash"></i> Delete</a>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="text-right"><a class="category-link" href="#top"><i class="fa fa-chevron-up"></i> Back to
                        the top</a></p>
                </section>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var class_column = 6;
        var csrftoken = "{{ csrf_token() }}"
    </script>
    <script src="{{ url_for('static', filename='js/jquery.autocomplete.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/select2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/records-search.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.tablesorter.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/sort-tables.js') }}"></script>
    <script src="{{ url_for('static', filename='js/chutney.js') }}"></script>
{% endblock %}

app/templates/site/event.html
{% extends 'base.html' %}

{% block title %}
    {{ event.name + ' Dates - University of Warwick Archery Club' }}
{% endblock %}

{% block extra_css %}
{% endblock %}

{% block main_content %}
    {% include "site/search-form.html" %}
    <div class="row">
        <div class="small-12 columns">
            <section class="bottom-divider">
                <h1>Dates for {{ event.name }}</h1>
            </section>
            <section>
                {% for category in categories %}
                    <a href="/records/event/{{ event.id }}/{{ category['date'] | urlencode }}" class="item-row">{{ category['date'] }}<span>View scores</span></a>
                {% endfor %}
            </section>
            <p class="text-right"><a href="#top"><i class="fa fa-chevron-up"></i> Back to top</a></p>
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var csrftoken = "{{ csrf_token() }}"
    </script>
    <script src="{{ url_for('static', filename='js/jquery.autocomplete.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/select2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/records-search.js') }}"></script>
{% endblock %}

app/templates/site/round.html
{% extends 'base.html' %}

{% block title %}
    {{ score_round.name + ' Scores - University of Warwick Archery Club' }}
{% endblock %}

{% block main_content %}
    {% include "site/search-form.html" %}
    <div class="row">
        <div class="small-12 columns">
            <section>
                <h1>{{ score_round.name }} scores</h1>
                <h4>Jump to:</h4>
                <ul>
                    {% for category in categories %}
                        <li>
                            <a class="category-link"
                               href="#{{ category['div_name'] | lower | strip_spaces }}">{{ category['div_name'] | expand_gender }}</a>
                        </li>
                    {% endfor %}
                </ul>
                {% if score_round.is_outdoors() %}
                    <p class="bottom-divider pad-bottom px-5"><strong>Note:</strong> Any classification with an asterix (<strong>*</strong>) needs to have been shot at a record-status event.</p>
                {% endif %}
            </section>
            {% for category in categories %}
                <section>
                    <h3 id="{{ category['div_name'] | lower | strip_spaces }}">{{ category['div_name'] | expand_gender | title }}</h3>
                    <table class="full-width sortable">
                        <thead>
                        <tr>
                            <th class="sort-header reverse">Name</th>
                            <th class="{sorter: 'scores'} sort-header sort-ascending">Score</th>
                            <th class="sort-header">Hits</th>
                            <th class="sort-header">Golds</th>
                            <th class="sort-header">Xs</th>
                            <th class="sort-header reverse">Experience</th>
                            <th>Classification</th>
                            <th class="sort-header">Date</th>
                            <th class="sort-header">Event</th>
                            {% if current_user.is_authenticated %}
                                <th>Actions</th>
                            {% endif %}
                        </tr>
                        </thead>
                        <tbody>
                        {% for score in category['scores'] %}
                            <tr>
                                <td><a href="/records/archer/{{ score.archer_id }}">{{ score.archer.get_name() }}</a></td>
                                <td>{{ score['score'] }}<span class="fade">/{{ category['max_score'] }}</span></td>
                                <td>{{ score['num_hits'] }}</td>
                                <td>{{ score['num_golds'] }}</td>
                                <td>{{ score['num_xs'] }}</td>
                                <td>{{ score['category'] }}</td>
                                <td>{{ score['classification'] if score['classification'] else '' }}</td>
                                <td>{{ score['date'] }}</td>
                                <td>{{ score.event.name }}</td>
                                {% if current_user.is_authenticated %}
                                    <td>
                                        <a class="admin-action"
                                           href="{{ url_for('admin.edit_score', score_id=score.id) }}?next={{ request.path | urlencode }}"><i
                                                class="fa fa-pencil"></i> Edit</a>
                                        <a class="admin-action"
                                           href="{{ url_for('admin.delete_score', score_id=score.id) }}?next={{ request.path | urlencode }}"><i
                                                class="fa fa-trash"></i> Delete</a>
                                    </td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    <p class="text-right"><a class="category-link" href="#top"><i class="fa fa-chevron-up"></i> Back to
                        the top</a></p>
                </section>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block extra_js %}
    <script type="text/javascript">
        var class_column = 6;
        var csrftoken = "{{ csrf_token() }}"
    </script>
    <script src="{{ url_for('static', filename='js/jquery.autocomplete.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/select2.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/records-search.js') }}"></script>
    <script src="{{ url_for('static', filename='js/jquery.tablesorter.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/sort-tables.js') }}"></script>
    <script src="{{ url_for('static', filename='js/chutney.js') }}"></script>
{% endblock %}