app/mod_site/controller.py
import json
from time import strptime, mktime
from datetime import date, datetime
from threading import Thread
import Levenshtein as lev
from flask import Blueprint, render_template, request, redirect, flash, url_for, abort
from app.models import IndividualRecords, BowTypes, db, Archers, Scores, Classifications, Rounds, Events, QueuedScores
from app import mail, app
from flask_mail import Message

mod_site = Blueprint('site', __name__, url_prefix='/records')


@mod_site.route('/', methods=['GET'])
def home():
    indoor_categories_shot = db.session.query(IndividualRecords.bow_type.distinct().label('bow_type')).filter(
        db.or_(IndividualRecords.round_type == 'Indoors', IndividualRecords.round_type == 'WA Indoors')).order_by(
        db.desc(IndividualRecords.bow_type)).all()
    indoor_categories = []

    for cat in indoor_categories_shot:
        category = {
            'name': cat.bow_type,
            'scores': IndividualRecords.query.filter(db.or_(IndividualRecords.round_type == 'Indoors',
                                                            IndividualRecords.round_type == 'WA Indoors')).filter(
                IndividualRecords.bow_type == cat.bow_type).order_by(IndividualRecords.round_name,
                                                                     db.desc(IndividualRecords.category),
                                                                     db.desc(IndividualRecords.score),
                                                                     db.desc(IndividualRecords.num_golds)).all()
        }

        indoor_categories.append(category)

    outdoor_categories_shot = db.session.query(
        IndividualRecords.bow_type.distinct().label('bow_type')).filter(
        db.not_(
            db.or_(IndividualRecords.round_type == 'Indoors', IndividualRecords.round_type == 'WA Indoors'))).order_by(
        db.desc(IndividualRecords.bow_type)).all()
    outdoor_categories = []

    for cat in outdoor_categories_shot:
        category = {
            'name': cat.bow_type,
            'scores': IndividualRecords.query.filter(db.not_(db.or_(IndividualRecords.round_type == 'Indoors',
                                                                    IndividualRecords.round_type == 'WA Indoors'))).filter(
                IndividualRecords.bow_type == cat.bow_type).order_by(IndividualRecords.round_name,
                                                                     db.desc(IndividualRecords.category),
                                                                     db.desc(IndividualRecords.score),
                                                                     db.desc(IndividualRecords.num_golds)).all()
        }

        outdoor_categories.append(category)

    bow_types = BowTypes.query.order_by(db.desc(BowTypes.name)).all()

    return render_template('site/search.html', bow_types=bow_types, indoor_categories=indoor_categories,
                           outdoor_categories=outdoor_categories)


@mod_site.route('/submit', methods=['POST'])
def submit():
    try:
        if not request.form['bow-select'] or \
                not request.form['archer-select'] or \
                not request.form['round-select'] or \
                not request.form['event-select'] or \
                not request.form['category-select'] or \
                not request.form['date-input'] or \
                not request.form['score-hits'] or \
                not request.form['score-score'] or \
                not request.form['score-golds'] or \
                not request.form['origin']:
            flash('Incomplete score', 'submission')
            return redirect(request.form['origin'])
    except KeyError:
        flash('Incomplete score', 'submission')
        return redirect('/records/')

    if 'score-xs' in request.form:
        if not request.form['score-xs']:
            flash('Incomplete score', 'submission')
            return redirect(request.form['origin'])

    if not is_integer(request.form['bow-select']) or \
            not is_integer(request.form['archer-select']) or \
            not is_integer(request.form['round-select']) or \
            not is_integer(request.form['event-select']) or \
            not is_category(request.form['category-select']) or \
            not is_date(request.form['date-input']) or \
            not is_integer(request.form['score-hits']) or \
            not is_integer(request.form['score-score']) or \
            not is_integer(request.form['score-golds']):
        flash('Incorrect score information', 'submission')
        return redirect(request.form['origin'])

    if 'score-xs' in request.form:
        if not is_integer(request.form['score-xs']):
            flash('Incorrect score information', 'submission')
            return redirect(request.form['origin'])

    if not db.session.query(db.exists().where(Archers.id == request.form['archer-select'])).scalar():
        flash('Archer doesn\'t exist', 'submission')
        return redirect(request.form['origin'])
    archer = Archers.query.get(request.form['archer-select'])

    if not db.session.query(db.exists().where(Rounds.id == request.form['round-select'])).scalar():
        flash('Round doesn\'t exist', 'submission')
        return redirect(request.form['origin'])
    score_round = Rounds.query.get(request.form['round-select'])

    if not db.session.query(db.exists().where(Events.id == request.form['event-select'])).scalar():
        flash('Event doesn\'t exist', 'submission')
        return redirect(request.form['origin'])
    event = Events.query.get(request.form['event-select'])

    if not db.session.query(db.exists().where(BowTypes.id == request.form['bow-select'])).scalar():
        flash('Bow type doesn\'t exist', 'submission')
        return redirect(request.form['origin'])
    bow_type = BowTypes.query.get(request.form['bow-select'])

    if int(request.form['score-hits']) not in range(0, score_round.max_hits + 1):
        flash('Incorrect number of hits', 'submission')
        return redirect(request.form['origin'])
    hits = int(request.form['score-hits'])

    if int(request.form['score-golds']) not in range(0, score_round.max_hits + 1):
        flash('Incorrect number of golds', 'submission')
        return redirect(request.form['origin'])
    golds = int(request.form['score-golds'])

    if 'score-xs' in request.form:
        if int(request.form['score-xs']) not in range(0, golds + 1):
            flash('Incorrect number of Xs', 'submission')
            return redirect(request.form['origin'])
        else:
            if score_round.r_type is 'Clout' or 'Indoors' in score_round.r_type:
                xs = None
            else:
                xs = int(request.form['score-xs'])
    else:
        if score_round.r_type is 'Clout' or 'Indoors' in score_round.r_type:
            xs = None
        else:
            xs = 0

    if int(request.form['score-score']) not in range(0, score_round.max_score + 1):
        flash('Incorrect score', 'submission')
        return redirect(request.form['origin'])
    score = int(request.form['score-score'])

    category = category_map(request.form['category-select'])
    score_date = date.fromtimestamp(mktime(strptime(request.form['date-input'], '%Y-%m-%d')))

    score_obj = QueuedScores(archer.id, score_round.id, event.id, bow_type.id, category, score, hits, golds, xs,
                             score_date)

    db.session.add(score_obj)
    db.session.commit()

    send_email(score_obj)

    flash('Score submitted successfully', 'submission')

    return redirect(request.form['origin'])


def send_email(score):
    msg = Message(
        'New score submitted by {name} at {datetime} for a {round} on {date}: {score}'.format(
            name=score.archer.get_name(), date=date.strftime(score.date, '%d/%m/%Y'), score=score.score,
            round=score.round.name, datetime=datetime.strftime(datetime.now(), '%d/%m/%Y %H:%M:%S')),
        recipients=app.config['MAIL_RECORDS']
    )
    msg.html = '{name} has submitted a score:<br/><br/>' \
               '{round} on {date} as {category}<br/>' \
               'Score: {score}, hits: {hits}, golds: {golds}, Xs: {xs}<br/><br/>' \
               'CSV format:<br/>' \
               '<pre>{name_csv},{cat_csv},{bow_csv},{round_csv},{date_csv},{event_csv},{score_csv},{hits_csv},' \
               '{golds_csv},{xs_csv},</pre><br/>' \
               'To approve the score click <a href="{approve}">here</a> or to reject click ' \
               '<a href="{reject}">this link</a><br/><br/>' \
               'This email was automatically generated, please don\'t reply.' \
        .format(name=score.archer.get_name(), round=score.round.name, date=date.strftime(score.date, '%d/%m/%Y'),
                category=score.category, score=score.score, hits=score.num_hits, golds=score.num_golds,
                xs=score.num_xs or 'N/A', name_csv=score.archer.get_name(),
                cat_csv=condense_category(score.archer.gender, score.category), bow_csv=score.bow.name,
                round_csv=score.round.name, date_csv=date.strftime(score.date, '%d/%m/%Y'), event_csv=score.event.name,
                score_csv=score.score, hits_csv=score.num_hits, golds_csv=score.num_golds, xs_csv=score.num_xs or '',
                approve=app.config['SITE_URL'] + url_for('admin.approve_score', score_id=score.id),
                reject=app.config['SITE_URL'] + url_for('admin.reject_score', score_id=score.id))

    thread = Thread(target=send_async_email, args=[msg])
    thread.start()


def send_async_email(msg):
    with app.app_context():
        mail.send(msg)


def condense_category(gender, experience):
    if experience in 'Experienced':
        if gender in 'M':
            return 'ME'
        elif gender in 'F':
            return 'FE'
        else:
            return None
    elif experience in 'Novice':
        if gender in 'M':
            return 'MN'
        elif gender in 'F':

app/templates/base.html
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="theme-color" content="#a70727">

    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}"/>
    <link rel="stylesheet" type="text/css"
          href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Lato:300,400,700">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/select2.min.css') }}"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/app.css') }}"/>

    <script src="{{ url_for('static', filename='bower_components/modernizr/modernizr.js') }}"></script>

    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                        (i[r].q = i[r].q || []).push(arguments)
                    }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                    m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-63461427-1', 'auto');
        ga('send', 'pageview');
    </script>

    <title>{% block title %}{% endblock %}</title>

    {% block extra_css %}{% endblock %}
</head>
<body class="flex-wrapper">
<section class="contain-to-grid fixed">
    <nav class="top-bar" data-topbar role="navigation">
        <ul class="title-area">
            <li class="name">
                <h1><a href="{{ config['SITE_URL'] }}/">UWAC</a></h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
        </ul>
        <section class="top-bar-section">
            <ul class="left">
                <li><a href="{{ config['SITE_URL'] }}/">Home</a></li>
                <li><a href="{{ config['SITE_URL'] }}/the-club">The Club</a></li>
                <li><a href="{{ config['SITE_URL'] }}/exec">Exec</a></li>
                <li><a href="{{ config['SITE_URL'] }}/sessions">Sessions</a></li>
                <li><a href="{{ config['SITE_URL'] }}/competitions">Competitons</a></li>
                <li class="{{ 'active' if 'records' in request.path else '' }}"><a href="{{ url_for('site.home') }}">Records</a>
                </li>
                <li><a href="{{ config['SITE_URL'] }}/contact-us">Contact Us</a></li>
            </ul>
        </section>
    </nav>
</section>

<section id="main-content" class="flex-content">
    {% block main_content %}{% endblock %}
</section>

<footer class="footer">
    <div class="row">
        <div class="small-12 large-3 columns">
            <h5>University of Warwick Archery Club</h5>
            <ul class="social-list">
                <li><a href="https://www.facebook.com/universityofwarwickarcheryclub"><span
                        class="fa fa-facebook-square fa-2x"></span></a></li>
                <li><a href="https://twitter.com/uwacfeed"><span class="fa fa-twitter-square fa-2x"></span></a></li>
                <li><a href="{{ config['SITE_URL'] }}/rss/"><span class="fa fa-rss-square fa-2x"></span></a></li>
            </ul>
        </div>
        <div class="small-12 large-9 columns">
            <ul class="sitemap-list">
                <li><a href="{{ config['SITE_URL'] }}/">Home</a></li>
                <li><a href="{{ config['SITE_URL'] }}/the-club">The Club</a></li>
                <li><a href="{{ config['SITE_URL'] }}/exec">Exec</a></li>
                <li><a href="{{ config['SITE_URL'] }}/sessions">Sessions</a></li>
                <li><a href="{{ config['SITE_URL'] }}/competitions">Competitions</a></li>
                <li><a href="{{ url_for('site.home') }}">Records</a></li>
                <li><a href="{{ config['SITE_URL'] }}/contact">Contact</a></li>
                <li><a href="/ghost">Ghost</a></li>
                <li><a href="{{ url_for('admin.dashboard') }}">Admin</a></li>
                {% if current_user.is_authenticated %}
                    <li><a href="{{ url_for('admin.logout') }}">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
    <div class="row">
        <p class="credits text-center">
            Copyright &copy; University of Warwick Archery Club. Built by <a href="https://github.com/davidjrichardson">David
            Richardson</a>. Powered by <a href="https://ghost.org/">Ghost</a> and <a href="https://flask.pocoo.org/">Flask</a>.
        </p>
    </div>
</footer>

<script src="{{ url_for('static', filename='bower_components/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='bower_components/slick-carousel/slick/slick.min.js') }}"></script>
<script src="{{ url_for('static', filename='bower_components/foundation/js/foundation.min.js') }}"></script>

<script src="{{ url_for('static', filename='js/app.js') }}"></script>

{% block extra_js %}{% endblock %}

</body>
</html>